import '../dashboard/model/production_model.dart';

class DummyProducts {
  static List<ProductionModel>? products = [
    ProductionModel(
      productionId: 1000001,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'CNC',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2022, 12, 21),
      requiredDate: DateTime.utc(2023, 2, 28),
      projectedDate: DateTime.now(),
      lastConfirmDate: DateTime.now(),
      revisionDate: DateTime.now(),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000005,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'PRES',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'BASKI',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'BASKI',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'BASKI',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'BASKI',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'TORNALAMA',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
    ProductionModel(
      productionId: 1000003,
      state: 1,
      revisionNo: 0,
      utCode: 'CNC-5455666',
      productCode: 'productCode',
      brand: 'EXTRUDER',
      model: 'model',
      vendor: 'vendor',
      customer: 'customer',
      endUser: 'endUser',
      shipPointCity: 'shipPointCity',
      shipPointCounty: 'shipPointCounty',
      shipPointAddress: 'shipPointAddress',
      shipType: 'shipType',
      orderNumber: 01,
      productionState: 1,
      orderDate: DateTime.utc(2023, 10, 9),
      requiredDate: DateTime.utc(2023, 7, 9),
      projectedDate: DateTime.utc(2023, 5, 9),
      lastConfirmDate: DateTime.utc(2023, 1, 9),
      revisionDate: DateTime.utc(2023, 11, 9),
      assemblyLocation: 'assemblyLocation',
      serialNumber: 'serialNumber',
    ),
  ];
}
